languageCode = "en"
title = "Tony Lawrence"
baseurl = "http://tonylawrence.com"

theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/tonyklawrence\">Tony Lawrence</a> 2017 - Waffly Bollocks"
disqusShortname = "tonylawrence"
googleAnalytics = ""

# Number of articles to show on the main page
Paginate = 8

[params]

[params.highlight]
#style = "tomorrow"
languages = ["java", "kotlin", "scala", "bash", "haskell"]

[[params.social]]
url = "https://github.com/tonyklawrence"
fa_icon = "fa-github"

[[params.social]]
url = "https://github.com/tonyklawrence"
fa_icon = "fa-bitbucket"

[[params.social]]
url = "https://twitter.com/tonyklawrence"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss" 
