version: '2'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:4.0.0-1
    hostname: pihole
    domainname: my.network
    mac_address: d0:ca:ab:cd:ef:01
    networks:
      home:
    ports:
      - 443/tcp
      - 53/tcp
      - 53/udp
      - 67/udp
      - 80/tcp
    environment:
      ServerIP: 1092.168.123.201
      WEBPASSWORD: ""
      VIRTUAL_HOST: pihole.my.network
      DNS1: 8.8.8.8
      DNS2: 8.8.4.4
    volumes:
      - /volume1/docker/dns/volume:/etc/pihole:rw
      - /volume1/docker/dns/config/hosts:/etc/hosts:ro
      - /volume1/docker/dns/config/resolv.conf:/etc/resolv.conf:ro
      - /volume1/docker/dns/config/dnsmasq.conf:/etc/dnsmasq.d/02-network.conf:ro
    restart: always

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: ovs_eth0
    ipam:
      config:
        - subnet: 192.168.123.0/24
          gateway: 192.168.123.1
          ip_range: 192.168.123/28
